Repository a1unade/bars-chat-bot, pull requests merged in 2025-07, with the labels that each got.

#54 [add realization]
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Interfaces/IDbContext.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Interfaces/INotificationLogRepository.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Persistence/Repositories/NotificationLogRepository.cs
Labels: enhancement

#57 [fix] repository-documentation
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Interfaces/INotificationLogRepository.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Persistence/Repositories/NotificationLogRepository.cs
Labels: bug

#61 [fix] deserializer-options
  NotifyHub.Kafka/NotifyHub.Kafka/Configurations/KafkaJsonDeserializer.cs
  NotifyHub.Kafka/NotifyHub.Kafka/NotifyHub.Kafka.csproj
Labels: bug

#68 [add] outbox-threading-processor + retry-policy-job
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.Infrastructure/NotifyHub.OutboxProcessor.Infrastructure.csproj
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.Infrastructure/Processors/OutboxProcessor.cs
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/appsettings.Development.json
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/appsettings.json
  docker-compose.yml
  prod/docker-compose.yml
  prod/generate-compose.sh
Labels: enhancement

#69 [add] kafka-messages + domain-events-abstractions
  NotifyHub.Abstractions/NotifyHub.Abstractions/DTOs/NotificationEventDto.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/DTOs/NotificationMessageDto.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/Events/BaseDomainEvent.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/Events/NotificationCreatedDomainEvent.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/Events/NotificationDeletedDomainEvent.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/Events/NotificationUpdatedDomainEvent.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/NotifyHub.Abstractions.csproj
Labels: enhancement

#74 [update] telegram-user-id
  NotifyHub.Abstractions/NotifyHub.Abstractions/DTOs/NotificationDto.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/DTOs/NotificationMessageDto.cs
  NotifyHub.Abstractions/NotifyHub.Abstractions/NotifyHub.Abstractions.csproj
Labels: enhancement

#77 [add] cqrs + fluent-validation
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Features/Queries/GetAllHistory/GetAllHistoryQueryHandler.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Features/Queries/GetHistoryById/GetHistoryByIdQueryHandler.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Application/Validators/IdRequestValidator.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Infrastructure/Behaviours/ValidationBehaviour.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.WebApi/Program.cs
Labels: enhancement

#83 [add] serilog + sentry
  NotifyHub.NotificationService/NotifyHub.NotificationService.WebApi/Configurations/SerilogConfiguration.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.WebApi/NotifyHub.NotificationService.WebApi.csproj
  NotifyHub.NotificationService/NotifyHub.NotificationService.WebApi/Program.cs
  NotifyHub.NotificationService/NotifyHub.NotificationService.WebApi/appsettings.json
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/Configurations/SerilogConfiguration.cs
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/NotifyHub.OutboxProcessor.WebApi.csproj
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/Program.cs
  NotifyHub.OutboxProcessor/NotifyHub.OutboxProcessor.WebApi/appsettings.json
  NotifyHub/NotifyHub.WebApi/Configurations/SerilogConfiguration.cs
  NotifyHub/NotifyHub.WebApi/NotifyHub.WebApi.csproj
  NotifyHub/NotifyHub.WebApi/Program.cs
  NotifyHub/NotifyHub.WebApi/appsettings.json
  docker-compose.yml
Labels: enhancement

#86 [add] graphql-mutatiomn-validators
  NotifyHub/NotifyHub.Application/Extensions/ServiceCollectionExtensions.cs
  NotifyHub/NotifyHub.Application/Features/Mutations/NotificationMutation.cs
  NotifyHub/NotifyHub.Application/Features/Mutations/UserMutation.cs
  NotifyHub/NotifyHub.Application/NotifyHub.Application.csproj
  NotifyHub/NotifyHub.Application/Validators/CreateNotificationRequestValidator.cs
  NotifyHub/NotifyHub.Application/Validators/CreateUserRequestValidator.cs
  NotifyHub/NotifyHub.Application/Validators/UpdateNotificationRequestValidator.cs
  NotifyHub/NotifyHub.Application/Validators/UpdateUserRequestValidator.cs
  NotifyHub/NotifyHub.Infrastructure/Configurations/GraphQLErrorFilter.cs
  NotifyHub/NotifyHub.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  NotifyHub/NotifyHub.Infrastructure/NotifyHub.Infrastructure.csproj
  README.md
Labels: enhancement

#91 [add] read + delete user's-notifications
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Extensions/ServiceCollectionExtensions.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Commands/DeleteUserNotification/DeleteUserNotificationCommand.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Commands/DeleteUserNotification/DeleteUserNotificationHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Events/UserCreatedDomainEventHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Queries/GetUserNotifications/GetUserNotificationsQuery.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Queries/GetUserNotifications/GetUserNotificationsQueryHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Interfaces/IGraphQlService.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Responses/DeleteNotificationResponse.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Responses/NotificationListResponse.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Domain/DTOs/TelegramUserDto.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Domain/DTOs/UserNotificationDto.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Domain/Events/UserCreatedDomainEvent.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Domain/NotifyHub.TelegramBot.Domain.csproj
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/UpdateHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Services/GraphQlService.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Persistence/Migrations/20250723230044_Init.Designer.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Persistence/Migrations/20250723230044_Init.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Persistence/Migrations/ApplicationDbContextModelSnapshot.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot/Program.cs
Labels: enhancement

#93 [fix] delete-mode-exit
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/UpdateHandler.cs
Labels: bug

#95 [add] create-notification
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Commands/CreateUserNotification/CreateUserNotificationCommand.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Features/Commands/CreateUserNotification/CreateUserNotificationCommandHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Interfaces/IGraphQlService.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Interfaces/INotificationService.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Application/Responses/CreateNotificationResponse.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Domain/DTOs/CreateNotificationDto.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Extensions/ServiceCollectionExtensions.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/BeginCreateNotificationHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/CreateNotificationMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/NotificationListMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Helpers/GraphQlEnumConverter.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Services/GraphQlService.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Services/NotificationService.cs
Labels: enhancement

#99 [add] final-additions
  GitVersion.yml
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/BeginCreateNotificationHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/BeginUpdateNotificationHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/CreateNotificationMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/DefaultMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/HelpMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/HistoryMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/NotificationListMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/StartMessageHandler.cs
  NotifyHub.TelegramBot/NotifyHub.TelegramBot.Infrastructure/Handlers/UpdateNotificationMessageHandler.cs
  docker-compose.yml
  materials/1.png
  materials/2.png
  prod/generate-compose.sh
Labels: enhancement

#100 [add] final-additions
  materials/2.png
Labels: documentation
